<a href="https://colab.research.google.com/github/vandana10/deeplearning-using-pytorch/blob/main/rag_app.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [5]:
scalar = torch.tensor(7)
scalar
scalar.ndim
# Get tensor back as Python int
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [9]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [12]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.0997, 0.1481, 0.2840, 0.3006],
        [0.2056, 0.4637, 0.9044, 0.7756],
        [0.0182, 0.3983, 0.1368, 0.1185]])


In [13]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [14]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [19]:
float_32_tensor.dtype

torch.float32

In [20]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [22]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [24]:
#getting info from tensors
#datatype = tensor.dtype
#shape = tensor.shape
#right device- tensor.device

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7620, 0.1631, 0.1067, 0.7258],
        [0.1441, 0.4323, 0.9632, 0.4695],
        [0.5584, 0.1317, 0.8851, 0.4313]])

In [26]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.size())
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu


### Manipulating tensor

tensor operations:
1. additon
2. sub
3. multuplication
4. div
5. matrix mul


In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor - 10

tensor([-9, -8, -7])

In [30]:
tensor * 10

tensor([10, 20, 30])

In [31]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [32]:
torch.add(tensor,12)

tensor([13, 14, 15])

Matrx multiplication
1. element wise multiplication
2. Matrix by another matrix (dot product)

In [33]:
tensor

tensor([1, 2, 3])

In [34]:
tensor * tensor

tensor([1, 4, 9])

In [35]:
#Matrix mul

In [36]:
torch.matmul(tensor,tensor)

tensor(14)

In [39]:
#rules for mat mul
# 1. inner dimension should work
# 2. resulting matric has shape of outer dimension
# eg: (2,3) * (3,2) -> (2,2)

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10]])

torch.matmul(tensor_A,tensor_B)


tensor([[ 25,  28],
        [ 57,  64],
        [ 89, 100]])

In [40]:
tensor_A.dtype

torch.int64

In [41]:
tensor_A.type(dtype = torch.float32)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [43]:
tensor_A.type(torch.float32).mean()

tensor(3.5000)

In [44]:
tensor_A.type(torch.float32).sum()

tensor(21.)

In [45]:
tensor_A.argmin()

tensor(0)

In [46]:
tensor_A.argmax() #returns index of max value

tensor(5)

In [48]:
x = torch.tensor([2,4,2,6,2,6,7,8,9,10])

###Reshaping, Stacking, Squeezing and unsqueezing

1. Reshaping - reshapes an i/p tensor to a defines shape
2. view - returns a view of an input of a certaoin shape but keep the same memory as org tensor
3. stack - combines multiple tensors on top of each other or side by side
4. squeeze -  removes all '1' dimension from a tensor
5. Unsqueeze -  adds a 1 Dimension to a target tensor
6. permute -return a view of the input with dimension permuted (swapped) in a certain way
